name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_SECRET }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
   
    - name: Build Docker Image
      run: docker build -t teena23/github_action_docker:latest .
   
    - name: Push Docker Image
      run: docker push teena23/github_action_docker:latest
      
    - name: Log out from Docker Hub  
      run: docker logout
    #steps:
    #- uses: actions/checkout@v4
    #- name: Login to Docker Hub
     # uses: docker/login-action@v3
      #with:
       # username: ${{ secrets.DOCKER_USERNAME }}
        #password: ${{ secrets.DOCKER_HUB_SECRET }}

    #- name: Build and Push Docker Image
     # uses: docker/build-push-action@v6
      #with:
       # push: true
        #tags: ${{ github.repository }}:${{ github.sha }}  # Tag with commit SHA
        #context: . #--file Dockerfile  # Build 
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag teena23/node.js:latest
    #- name: Push to docker hub
      #uses: docker/build-push-action@v6
      #with: 
        #docker login --help
        #username: ${{ secrets.DOCKER_USERNAME }} 
        #password: ${{ secrets.DOCKER_HUB_SECRET }} 
        #repository: teena23/teena23_node.js
        #push: true
        #tags: teena23/teena23_node.js:latest

       # docker push teena23/teena23_node.js:latest


