name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag teena23/node.js:latest
    - name: Push to docker hub
      uses: docker/build-push-action@v6
      with: 
        #docker login --help
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_HUB_SECRET }} 
        #repository: teena23/teena23_node.js
        #push: true
        #tags: teena23/teena23_node.js:latest

       # docker push teena23/teena23_node.js:latest


