# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Docker Image
on: push
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v4
      - name: Build the docker image
        run: docker build . --file Dockerfile --tag my-image-name:${date +%s}
        #uses: actions/setup-node@v4
        #with:
       #   node-version: 20
      #- run: node --version
      #- run: npm --version
      #- run: npm install
      #- run: npm run build --if-present
     # - run: npm install --save-dev jest
      #- run: npm test


